### ISSUE TITLE
Netlify redirects creation creates build error on Travis

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/tsb-react-map-boilerplate#4]
re #3 

https://github.com/technologiestiftung/tsb-react-map-boilerplate/blob/86fd873e98bcd8eaf5b2b530a296cc0dc046f41b/package.json#L37

@fdnklg What is the purpose of this line

**Comment by fdnklg** [comment]
It's necessary to prevent the _Page not found_ Error of Netlify if a url is not found and redirects to index.html. This is a common issue at netlify.

**Comment by fabianmoronzirfas** [comment]
Well your script still throws an error. Did you test this locally?
Shouldn't this be `${echo '/* /index.html  200' > build/_redirects}`

**Comment by fabianmoronzirfas** [comment]
Sorry. The issue came not from the script. It was the build error.
